version: '3'

services:
    redis-server:
        image: redis
        ports:
            - 6379:6379
                

            
    mysqldb:
        image: mysql
        container_name: mysqldb
        ports:
            - 3310:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: stajzt
            
        volumes:
            - ./stajdb.sql:/docker-entrypoint-initdb.d/stajdb.sql
            - ./mysql-vol/:/var/lib/mysql
            
    node-back:
        build: ./node-back
        ports:
            - 10000:10000
        depends_on:
            - mysqldb